LinkExchange/Controllers/AdvertiserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LinkExchange.Controllers
{
    [Authorize]
    public class AdvertiserController : Controller
    {
        //
        // GET: /Advertiser/

        public ActionResult Index()
        {
            return View();
        }

    }
}

LinkExchange/Controllers/MoneyController.cs
using LinkExchange.Models;
using RomanPushkin.BetterRobokassa;
using System;
using System.Collections.Generic;
using System.Data;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LinkExchange.Controllers
{
    public class MoneyController : Controller
    {
        private HelpContext db = new HelpContext();
        private UserProfile us;
        public ActionResult Index(string price, RobokassaConfirmationRequest confirmationRequest)
        {
            us = (UserProfile) db.UserProfiles.Where(u => u.UserName == User.Identity.Name).First();
            ViewBag.balance = us.Balance;

            if (string.IsNullOrEmpty(price))
            {
                if (confirmationRequest.InvId>0)
                {
                    
                        if (!string.IsNullOrEmpty(confirmationRequest.SignatureValue))
                        {
                            processOrder(confirmationRequest);
                            return Redirect("~/Money?success=true");
                        }
                        else
                        {
                            return Redirect("~/Money?success=false");
                        }
                    
                }
                return View();
            }
            else
            {
                string redirectUrl = Robokassa.GetRedirectUrl(int.Parse(price), us.UserId);
                return Redirect(redirectUrl);
            }
        }

        private void processOrder(RobokassaConfirmationRequest confirmationRequest)
        {
            if (db.InOperations.Where(op => op.TranId == confirmationRequest.SignatureValue).Count() == 0) {
                us.Balance += double.Parse(confirmationRequest.OutSum, CultureInfo.InvariantCulture);
                db.Entry(us).State = EntityState.Modified;

                var op = new InOp();
                op.userId = us.UserId;
                op.TranId = confirmationRequest.SignatureValue;
                op.sum = double.Parse(confirmationRequest.OutSum, CultureInfo.InvariantCulture);
                op.time = DateTime.Now;
                db.InOperations.Add(op);

                db.SaveChanges();
            }

        }

    }
}

LinkExchange/Controllers/WebmasterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LinkExchange.Controllers
{
    public class WebmasterController : Controller
    {
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }
    }
}

LinkExchange/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <title>@ViewBag.Title – приложение ASP.NET MVC</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/themes/base/css")
</head>
<body>
    <div id="wrapper">
            @Html.Partial("_UserSettings")
            @RenderBody()
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

LinkExchange/Views/Shared/_UserSettings.cshtml
@if (Request.IsAuthenticated)
{
    <nav class="navbar navbar-default navbar-static-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Биржа ссылок</a>
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Оптимизатор", "Index", "Advertiser", routeValues: new { area = "" }, htmlAttributes: new { title = "Оптимизатор" })</li>
                    <li>@Html.ActionLink("Вебмастер", "Index", "Webmaster", routeValues: new { area = "" }, htmlAttributes: new { title = "Вебмастер" })</li>
                    <li>@Html.ActionLink("Финансы", "Index", "Money", routeValues: new { area = "" }, htmlAttributes: new { title = "Финансы" })</li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Здравствуйте, @User.Identity.Name<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Личный кабинет", "Manage", "Account", routeValues: new { area = "" }, htmlAttributes: new { @class = "username", title = "Личный кабинет" })</li>
                            <li class="divider"></li>
                            <li><a href="javascript:document.getElementById('logoutForm').submit()">Выйти</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    using (Html.BeginForm("LogOff", "Account", new { area = "" }, FormMethod.Post, new { id = "logoutForm" }))
    {@Html.AntiForgeryToken()}
}